# Generated by Django 3.0.3 on 2020-06-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idea_model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=1000)),
                ('answers', models.TextField(max_length=10000)),
            ],
        ),
    ]
